# Generated by Django 5.2 on 2025-04-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=1000)),
                ('email', models.CharField(default='', max_length=1000)),
                ('password', models.CharField(default='', max_length=1000)),
                ('uname', models.CharField(default='', max_length=1000)),
                ('checkPoint', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
