# Generated by Django 5.2 on 2025-04-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_users_balance_alter_users_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='curr',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
