# Generated by Django 5.2 on 2025-04-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_users_curr'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False)),
                ('exRate', models.CharField(default='', max_length=1000)),
                ('name', models.CharField(default='', max_length=10000)),
            ],
        ),
    ]
