# Generated by Django 5.2 on 2025-04-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_currencyrate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='name',
            field=models.CharField(default='', max_length=10000, unique=True),
        ),
    ]
