# Generated by Django 5.2 on 2025-04-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_currencyrate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='name',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
